# Generated by Django 5.2.7 on 2026-05-01 12:08

import django.db.models.deletion
import userauths.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cart_cartorder_cartorderitem_coupon_notification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, default='brand.jpg', null=True, upload_to=userauths.models.user_directory_path)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='ConfigSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_more', models.CharField(default='View All', max_length=10)),
                ('currency_sign', models.CharField(default='$', max_length=10)),
                ('currency_abbreviation', models.CharField(default='USD', max_length=10)),
                ('service_fee_percentage', models.IntegerField(default=5, help_text='NOTE: Numbers added here are in percentage (%)ve.g 4%')),
                ('service_fee_flat_rate', models.DecimalField(decimal_places=2, default=0.7, help_text='NOTE: Add the amount you want to charge as service fee e.g $2.30', max_digits=12)),
                ('service_fee_charge_type', models.CharField(choices=[('percentage', 'Percentage'), ('flat_rate', 'Flat Rate')], default='percentage', max_length=30)),
                ('enforce_2fa', models.BooleanField(default=True)),
                ('activate_affiliate_system', models.BooleanField(default=True)),
                ('send_email_notifications', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.CreateModel(
            name='DeliveryCouriers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('tracking_website', models.URLField(blank=True, null=True)),
                ('url_parameter', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Delivery Couriers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=500)),
                ('rate', models.IntegerField(default=5, help_text='Numbers added here are in percentage (5 = 5%)')),
                ('active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Tax',
            },
        ),
        migrations.CreateModel(
            name='CancelledOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('refunded', models.BooleanField(default=False)),
                ('orderitem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.cartorderitem')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cancelled Order',
            },
        ),
        migrations.CreateModel(
            name='CouponUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=1000)),
                ('mobile', models.CharField(max_length=1000)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.coupon')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.cartorder')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=30, unique=True, verbose_name='Tag slug')),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='store.category', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Tags',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('town_city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('same_as_billing_address', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address_country', to='store.tax')),
            ],
            options={
                'verbose_name_plural': 'Address',
            },
        ),
    ]
