# Generated by Django 5.2.7 on 2026-05-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_cartorder_options_alter_cartorderitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
